In [1]:

import pandas as pd
import numpy as np
from scipy import stats

In [3]:
#dataset
titanic = pd.read_csv("titanic.csv")

# Vistazo
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
#Prob. Supervicencia de un niño
children = titanic[titanic["age"] < 18]

prob_survive_child = children["survived"].mean()
prob_survive_child

np.float64(0.5398230088495575)

In [7]:
#probabilidad de que una mujer viaje sola

women = titanic[titanic["sex"] == "female"]

prob_woman_alone = (women["alone"] == True).mean()
prob_woman_alone

np.float64(0.4012738853503185)

In [11]:
#probabilidad de sobrevivir un hombre de 30-40 años, en southampton y sin pagar billete

subset = titanic[
    (titanic["sex"] == "male") &
    (titanic["age"].between(30, 40)) &
    (titanic["embarked"] == "S") &
    (titanic["fare"] == 0)
]

prob_survive = subset["survived"].mean()
prob_survive

np.float64(0.0)

In [12]:
#y acompañado de 2 familiares

subset_family = subset[(subset["sibsp"] + subset["parch"]) == 2]

prob_survive_family = subset_family["survived"].mean()
prob_survive_family

nan

In [16]:
#Intervalo 95% para supervivencia viajando solo

alone = titanic[titanic["alone"] == True]

p = alone["survived"].mean()
n = len(alone)

z = 1.96
se = np.sqrt((p * (1 - p)) / n)

ci_lower = p - z * se
ci_upper = p + z * se

(ci_lower, ci_upper)

(np.float64(0.264649401563202), np.float64(0.3424269485299079))

In [18]:
#solo en 2 o 3 clase

subset_extra = titanic[
    (titanic["class"].isin(["Second", "Third"])) &
    (titanic["alone"] == True)
]

p_extra = subset_extra["survived"].mean()
n_extra = len(subset_extra)

se_extra = np.sqrt((p_extra * (1 - p_extra)) / n_extra)

ci_lower_extra = p_extra - z * se_extra
ci_upper_extra = p_extra + z * se_extra

(ci_lower_extra, ci_upper_extra)

(np.float64(0.20456220775606815), np.float64(0.2860919978514085))

In [25]:
import pandas as pd
from scipy import stats

# Cargar dataset
life = pd.read_csv("lifesat_full.csv")

# Comprobar que cargó bien
life.head()

,Country,GDP per capita (USD),Life satisfaction,Life expectancy,Homicide rate,Employment rate
0,South Africa,11466.189672,4.725336,57.5,13.7,43.0
1,Colombia,13441.492952,6.302556,76.2,24.5,67.0
2,Brazil,14063.982505,6.415187,74.8,26.7,61.0
3,Mexico,17887.750736,6.536861,75.4,18.1,61.0
4,Chile,23324.524751,6.538143,79.9,4.2,63.0

In [26]:
#LIFE SATISFACTION

#99% que la media es <7

mean = life["Life satisfaction"].mean()

t_stat, p_value = stats.ttest_1samp(life["Life satisfaction"], 7)
p_value_one_tail = p_value / 2

mean, p_value_one_tail

(np.float64(6.599421401893583), np.float64(0.0019519917704683323))

In [27]:
#Nivel medio con vida >65 y empleo >60%

subset = life[
    (life["Life expectancy"] > 65) &
    (life["Employment rate"] > 60)
]

mean_subset = subset["Life satisfaction"].mean()
mean_subset

np.float64(6.74614501634108)

In [ ]:
#probabilidad de insatisfaccion en ese grupo

np.float64(6.74614501634108)

In [29]:
prob = (subset["Life satisfaction"] > 6).mean()
prob

np.float64(0.78125)